[package]
name = "tch-crf"
version = "0.7.2"
edition = "2021"

[dependencies]
candle-core = { git = "https://github.com/kigichang/candle.git", version = "0.6.1"}
candle-nn = { git = "https://github.com/kigichang/candle.git", version = "0.6.1"}